function H = hamiltonian(in1,in2,alpha)
%HAMILTONIAN
%    H = HAMILTONIAN(IN1,IN2,ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    13-Jan-2019 21:13:36

lambda1 = in1(3,:);
lambda2 = in1(4,:);
u1 = in1(5,:);
x2 = in1(2,:);
H = lambda2.*u1+lambda1.*x2+u1.^2.*5.0e-1;
