function [hy,hz,hp,gy,gz,gp] = difference_DAE(in1,in2,alpha)
%DIFFERENCE_DAE
%    [HY,HZ,HP,GY,GZ,GP] = DIFFERENCE_DAE(IN1,IN2,ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    13-Jan-2019 22:22:06

hy = sparse([1,4],[2,3],[1.0,-1.0],4,4);
if nargout > 1
    hz = sparse([2],[1],[1.0],4,1);
end
if nargout > 2
    hp = sparse([],[],[],4,4);
end
if nargout > 3
    gy = sparse([1],[4],[1.0],1,4);
end
if nargout > 4
    gz = sparse(1.0);
end
if nargout > 5
    gp = sparse([],[],[],1,4);
end
